language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t rdevcd2020/port-app-test -f ./target-portfolio/Dockerfile.dev ./target-portfolio

script:
  - docker run -e CI=true rdevcd2020/portfolio-app yarn test --coverage

after_success:
  - docker build -t rdevcd2020/port-app-prod-feb7 .
  # Login to docker CLI
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push the image to docker hub
  - docker push rdevcd2020/port-app-prod-feb7
  # deploy:
#   provider: script
#   script: deploy.sh
#   on:
#     branch: master
# endpoints:
#   https://api.travis-ci.org/:
#     access_token: $GITHUB_API_TOKEN
#   https://api.travis-ci.com/:
#     access_token: $GITHUB_API_TOKEN

# addons:
#   ssh_known_hosts: 157.245.252.42

# - openssl aes-256-cbc -K $encrypted_64b142302ac3_key -iv $encrypted_64b142302ac3_iv
# -in test_travis_rsa.enc -out ~\/.ssh/test_travis_rsa -d
