language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t rdevcd2020/portfolio-app -f Dockerfile.dev ./target-portfolio

script:
  - docker run -e CI=true rdevcd2020/portfolio-app yarn test --coverage
