endpoints:
  https://api.travis-ci.org/:
    access_token: $GITHUB_TOKEN
  https://api.travis-ci.com/:
    access_token: $GITHUB_TOKEN


language: generic

sudo: required


services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_64b142302ac3_key -iv $encrypted_64b142302ac3_iv
  -in test_travis_rsa.enc -out ~\/.ssh/test_travis_rsa -d
  - docker build -t rdevcd2020/portfolio-app -f ./target-portfolio/Dockerfile.dev ./target-portfolio

script: 
  - docker run -e CI=true rdevcd2020/portfolio-app yarn test --coverage

