language: generic
sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_64b142302ac3_key -iv $encrypted_64b142302ac3_iv
  -in test_travis_rsa.enc -out ~\/.ssh/test_travis_rsa -d
- docker build -t rdevcd2020/port-app-test -f ./target-portfolio/Dockerfile.dev ./target-portfolio
script:
- docker run -e CI=true rdevcd2020/port-app-test yarn test -- --coverage
after_success:
- docker build -t rdevcd2020/port-app-prod-feb8 .
- echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
- docker push rdevcd2020/port-app-prod-feb8
